"""Standalone aggregate dashboard. Deliberately excludes private text and IDs."""
import json

def make_dashboard(summary,monthly,path,cross=None):
    validation_path=path.parent/'validation.json'
    validation=json.loads(validation_path.read_text()) if validation_path.is_file() else None
    payload=json.dumps({'summary':summary,'monthly':monthly,'validation':validation,'cross':cross or []}).replace('<','\\u003c')
    template=r'''<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Vireo · Support decisions</title>
<style>
:root{font-family:system-ui,sans-serif;color:#20303f;background:#f3f5f4}body{max-width:1180px;margin:0 auto;padding:32px}h1{font-size:34px;letter-spacing:-1px;margin:8px 0}h2{font-size:20px}small,.muted{color:#576971}.eyebrow{font-size:12px;letter-spacing:2px;color:#247466;font-weight:700}.cards{display:grid;grid-template-columns:repeat(3,1fr);gap:16px;margin:24px 0}.card,section{background:white;border:1px solid #dce3df;border-radius:12px;padding:22px;margin-bottom:18px}.card strong{display:block;font-size:30px;margin:8px 0}.notice{border-left:4px solid #be8533;padding:12px 16px;background:#fff6e5;border-radius:4px}.controls{display:flex;flex-wrap:wrap;gap:18px;align-items:end;margin:18px 0}label{font-size:13px;display:block}select,input,button{font:inherit;padding:9px;border:1px solid #c2cec7;border-radius:6px;background:white}button{background:#146450;color:white;cursor:pointer}.chart{overflow-x:auto}.legend{display:flex;flex-wrap:wrap;gap:12px;font-size:12px}.swatch{display:inline-block;width:10px;height:10px;margin-right:5px}table{border-collapse:collapse;width:100%;font-size:13px}td,th{padding:11px 8px;text-align:left;border-bottom:1px solid #e3e9e5}th{color:#597069}textarea{box-sizing:border-box;width:100%;padding:12px;font:inherit;border:1px solid #c2cec7;border-radius:6px}summary{cursor:pointer;font-weight:600}code{font-size:12px}.screen{background:#153f37;color:white}.screen p{color:#d6e8df}.screen a{color:white}@media(max-width:700px){body{padding:16px}.cards{grid-template-columns:1fr}h1{font-size:28px}}
</style>
<header><div class="eyebrow">VIREO AUDIO / DECISION BRIEF</div><h1>Fix routing before approving hires.</h1><p class="muted">January 2025 – June 2026 · Ticket creation month · IST · Offline analysis</p></header>
<div class="cards"><div class="card"><small>Tickets in reporting window</small><strong id="tickets"></strong><small id="outside"></small></div><div class="card"><small>Q2 eligible routing opportunities</small><strong id="opportunities"></strong><small>Billing → delivery issue → Logistics · at least one transfer</small></div><div class="card"><small>Quarterly target at stated Vireo volume</small><strong id="saving"></strong><small>50% avoidance assumption · ₹305 per hand-off · proposed savings</small></div></div>
<div class="notice">Do not award two hires by intake volume alone. Recorded resolving team is an ownership proxy; elapsed resolution time is not agent workload. Tier 2 needs a separate capacity assessment.</div>
<section><h2>Monthly breakdown</h2><div class="controls"><div><label for="basis">Counting basis</label><select id="basis"><option>Opening text</option><option>Opening + closing text</option><option>Exported tag</option><option>First assigned team</option><option>Recorded agent team</option></select></div><div><label for="teambasis">Team filter basis</label><select id="teambasis"><option value="initial_team">First assigned</option><option value="recorded_agent_team">Recorded agent</option></select></div><div><label for="teamfilter">Team</label><select id="teamfilter"><option value="All">All teams</option></select></div><div><label for="from">From month</label><input id="from" type="month" value="2025-01" min="2025-01" max="2026-06"></div><div><label for="to">To month</label><input id="to" type="month" value="2026-06" min="2025-01" max="2026-06"></div><button id="download">Download filtered CSV</button></div><p id="basisnote" class="muted"></p><div class="chart" id="chart"></div><div class="legend" id="legend"></div><p id="total" class="muted"></p><details><summary>Accessible data table</summary><div id="monthlytable"></div></details></section>
<section><h2>Initial queue versus recorded resolving team</h2><div id="routing"></div><p class="muted">Counts use creation month and dated agent assignments at resolution; open/pending rows use creation date. This is not completed throughput by resolution month and does not reconstruct all intermediate transfers.</p></section>
<section><h2>Business goal: remove half the eligible detours</h2><p id="case"></p><div id="sensitivity"></div><p class="muted">Conservative scope: count one avoidable hand-off per qualifying ticket. No assumed improvement in refunds, SLA credits, repeat contacts or staffing costs is added. Routing effectiveness must be measured in a pilot.</p></section>
<section><h2>Try an opening-message classification</h2><textarea id="message" rows="3">Payment successful but order not delivered, tracking has not updated.</textarea><div class="controls"><button id="predict">Classify locally</button><span class="muted">Requires python serve.py; the static file remains usable for charts.</span></div><pre id="prediction" style="white-space:pre-wrap"></pre></section>
<section><h2>Review and data quality</h2><div id="quality"></div><p class="muted">Missing transfers remain unknown. Legacy resolutions receive +05:30 only. Refund currency units remain unresolved; no refund-value business case. Classification uses synthetic examples, not existing tags, roster teams or refund codes. Similarity is not confidence probability.</p><p id="validation">Validation report: see validation.json and validation.md in the submission pack. Assistant review is not independent human ground truth.</p></section>
<section class="screen"><h2>Monday handoff</h2><p>1. Run the README commands using private CSVs; do not publish row-level outputs.<br>2. Review uncertainty and opening/closing disagreements before operational decisions.<br>3. Pilot direct delivery routing for four weeks, review 30 flagged tickets weekly, and confirm Finance savings from actual avoided transfers.</p></section>
<script>const DATA=__PAYLOAD__;const S=DATA.summary;const $=id=>document.getElementById(id);const money=n=>'₹'+Math.round(n).toLocaleString('en-IN');const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));const palette=['#176754','#489180','#789950','#a5b676','#364e70','#708da6','#ac7352','#d2a172','#735e88','#ae91b8','#717c70','#9cac9d','#b29036','#c1c7cc'];
$('tickets').textContent=S.tickets.toLocaleString();$('outside').textContent=(S.diagnostics.outside_window||0)+' records excluded outside the requested window';$('opportunities').textContent=S.business_case.opportunities;$('saving').textContent=money(S.business_case.at_vireo_quarter_target_inr);
if(S.data_kind==='synthetic_demo'){document.querySelector('h1').textContent='Synthetic demonstration — not Vireo evidence';document.querySelector('header p').textContent='Authored toy inputs · These totals are not customer findings';}if(DATA.validation){let V=DATA.validation;$('validation').textContent='Frozen-model assistant-reviewed sample: '+V.sample_size+' tickets. Intake: '+V.accepted+' accepted, '+V.wrong_accepted+' wrong, '+V.abstained+' review ('+(100*V.error_rate_among_accepted).toFixed(2)+'% error among accepted). Retrospective: '+V.retrospective.accepted+' accepted, '+V.retrospective.wrong_accepted+' wrong, '+V.retrospective.abstained+' review. Same AI assistant reviewed the labels; no independent human ground truth.';}
function table(headers,rows){return '<table><thead><tr>'+headers.map(h=>'<th scope="col">'+esc(h)+'</th>').join('')+'</tr></thead><tbody>'+rows.map(r=>'<tr>'+r.map(c=>'<td>'+esc(c??'Unknown')+'</td>').join('')+'</tr>').join('')+'</tbody></table>'}
for(const t of [...new Set(DATA.cross.map(r=>r.initial_team).concat(DATA.cross.map(r=>r.recorded_agent_team)))].sort())$('teamfilter').innerHTML+='<option>'+esc(t)+'</option>';
function filtered(){if($('teamfilter').value==='All'||!DATA.cross.length)return DATA.monthly.filter(r=>r.basis===$('basis').value&&r.month>=$('from').value&&r.month<=$('to').value);const field={'Exported tag':'exported_tag','Opening text':'opening_category','Opening + closing text':'retrospective_category','First assigned team':'initial_team','Recorded agent team':'recorded_agent_team'}[$('basis').value],counts=new Map();for(const r of DATA.cross){if(r[$('teambasis').value]!==$('teamfilter').value||r.month<$('from').value||r.month>$('to').value)continue;const key=r.month+'|'+r[field],prev=counts.get(key);if(prev)prev.tickets+=r.tickets;else counts.set(key,{month:r.month,basis:$('basis').value,category:r[field],tickets:r.tickets});}return [...counts.values()]}
function draw(){const rs=filtered(),months=[...new Set(rs.map(r=>r.month))].sort(),cats=[...new Set(rs.map(r=>r.category))].sort();let total=rs.reduce((a,r)=>a+r.tickets,0);$('total').textContent=total.toLocaleString()+' tickets in selected range';$('basisnote').textContent=$('basis').value==='Opening + closing text'?'Retrospective only: closing notes are unavailable at intake. Conflicting classifications go to Needs review.':'Every ticket contributes once. Needs review remains a visible category; it is never silently forced into Other.';if(!months.length){$('chart').textContent='No data in this month range.';$('legend').innerHTML='';$('monthlytable').innerHTML='';return}const width=Math.max(750,months.length*54+90),height=300,left=50,top=20,bottom=45,plotH=height-top-bottom,max=Math.max(...months.map(m=>rs.filter(r=>r.month===m).reduce((a,r)=>a+r.tickets,0)));let svg='<svg role="img" aria-label="Monthly stacked ticket counts by selected category or team" viewBox="0 0 '+width+' '+height+'" width="'+width+'" height="'+height+'">';for(let i=0;i<=4;i++){let value=Math.ceil(max/4*i),y=height-bottom-value/max*plotH;svg+='<line x1="'+left+'" y1="'+y+'" x2="'+(width-10)+'" y2="'+y+'" stroke="#e3e9e5"/><text x="'+(left-8)+'" y="'+(y+4)+'" text-anchor="end" font-size="11" fill="#53655b">'+value+'</text>'}months.forEach((m,i)=>{let y=height-bottom,x=left+i*(width-left-10)/months.length+8,bw=(width-left-10)/months.length-16;cats.forEach((cat,j)=>{let n=rs.find(r=>r.month===m&&r.category===cat)?.tickets||0,h=n/max*plotH;y-=h;svg+='<rect x="'+x+'" y="'+y+'" width="'+bw+'" height="'+h+'" fill="'+palette[j%palette.length]+'"><title>'+esc(m+' · '+cat+': '+n)+'</title></rect>'});svg+='<text x="'+(x+bw/2)+'" y="'+(height-18)+'" text-anchor="middle" font-size="10" fill="#53655b">'+m.slice(2)+'</text>'});svg+='</svg>';$('chart').innerHTML=svg;$('legend').innerHTML=cats.map((c,j)=>'<span><i class="swatch" style="background:'+palette[j%palette.length]+'"></i>'+esc(c)+'</span>').join('');$('monthlytable').innerHTML=table(['Month','Category/team','Tickets'],rs.map(r=>[r.month,r.category,r.tickets]))}
['basis','from','to','teambasis','teamfilter'].forEach(id=>$(id).addEventListener('change',draw));$('download').onclick=()=>{let text='month,basis,category,tickets\n'+filtered().map(r=>[r.month,r.basis,r.category,r.tickets].map(v=>'"'+String(v).replaceAll('"','""')+'"').join(',')).join('\n'),url=URL.createObjectURL(new Blob([text],{type:'text/csv'})),a=document.createElement('a');a.href=url;a.download='vireo-monthly.csv';a.click();URL.revokeObjectURL(url)};
$('routing').innerHTML=table(['Team','Initially assigned','Recorded agent','Median resolution hours','CSAT responses','Mean CSAT'],S.team_stats.map(r=>[r.team,S.initial_teams[r.team]||0,r.recorded_agent_tickets,r.median_resolution_hours,r.csat_n,r.csat_mean]));const B=S.business_case;$('case').textContent='Q2 baseline: '+B.opportunities+' eligible tickets / '+B.quarter_tickets+' tickets = '+(B.opportunity_rate*100).toFixed(2)+'%. Goal: halve this rate to '+(B.opportunity_rate*50).toFixed(2)+'%. At the export’s volume, '+B.opportunities+' × 50% × ₹305 = '+money(B.observed_quarter_target_inr)+' per quarter. At the brief’s 650/week: 650 × 13 × '+(B.opportunity_rate*100).toFixed(2)+'% × 50% × ₹305 = '+money(B.at_vireo_quarter_target_inr)+'.';$('sensitivity').innerHTML=table(['Avoidance assumption','Observed Q2 savings','At 650 tickets/week'],B.sensitivity.map(r=>[(100*r.avoidance)+'%',money(r.observed_quarter_inr),money(r.at_vireo_quarter_inr)]));$('quality').innerHTML=table(['Check','Count'],Object.entries(S.diagnostics).map(([k,v])=>[k.replaceAll('_',' '),v]));$('predict').onclick=async()=>{try{const r=await fetch('/api/classify',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({message:$('message').value})});if(!r.ok)throw Error('Server returned '+r.status);$('prediction').textContent=JSON.stringify(await r.json(),null,2)}catch(e){$('prediction').textContent='Start the local tool with: python serve.py\n'+e.message}};draw();</script></html>'''
    path.write_text(template.replace('__PAYLOAD__',payload),encoding='utf-8')
